"""empty message

Revision ID: 199d1cdb2f72
Revises: b1ff8c0c89f1
Create Date: 2023-03-08 15:03:57.731279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199d1cdb2f72'
down_revision = 'b1ff8c0c89f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posters', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
